[versions]
agp = "8.13.1"
androidx-activityCompose = "1.11.0"
androidx-lifecycle = "2.9.6"
cmpEasyPermission = "1.0.3"
compose-multiplatform = "1.9.3"
filekitCompose = "0.8.8"
kermit = "2.0.8"
kotlin = "2.2.21"
kotlinxDatetime = "0.7.1"
gradle-buildconfig-plugin = "5.7.1"
biometric = "1.1.0"

ksp = "2.3.2"
androidx-room = "2.8.3"
androidx-sqlite = "2.6.1"
navigationCompose = "2.9.1"
posthogAndroid = "3.26.0"
sqlite = "2.5.2"

androidx-material = "1.10.0-alpha04"
androidx-icons = "1.7.8"

koin = "4.1.1"

kotlinSerialization = "1.9.0"

coroutines = "1.10.2"

google-gms = "4.4.4"
firebase-bom = "34.5.0"

ktor = "3.3.2"

androidBrowser = "1.9.0"
workRuntimeKtx = "2.11.0"

sp24-kt = "v2025.10.2"
activity = "1.8.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

androidx-material = { module = "org.jetbrains.compose.material3:material3", version.ref = "androidx-material" }
androidx-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-icons" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }

androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-sqlite-framework = { group = "androidx.sqlite", name = "sqlite-framework", version.ref = "androidx-sqlite" }
cmp-easy-permission = { module = "network.chaintech:cmp-easy-permission", version.ref = "cmpEasyPermission" }
filekit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "filekitCompose" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
posthog-android = { module = "com.posthog:posthog-android", version.ref = "posthogAndroid" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "androidx-sqlite" }

firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

androidx-browser = { module = "androidx.browser:browser", version.ref = "androidBrowser" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

vpp-sp24 = { module = "plus.vplan.lib:sp24-kt", version.ref = "sp24-kt" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

room = { id = "androidx.room", version.ref = "androidx-room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref="kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }
google-gms = { id = "com.google.gms.google-services", version.ref = "google-gms" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "gradle-buildconfig-plugin" }

stability-analyzer = { id = "com.github.skydoves.compose.stability.analyzer", version = "0.5.1" }
